//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TuLista.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tabArticulo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tabArticulo()
        {
            this.tabCompraArticulos = new HashSet<tabCompraArticulos>();
        }
    
        public int Id { get; set; }
        public Nullable<int> IdTipo { get; set; }
        public string Articulo { get; set; }
        public Nullable<int> usos { get; set; }
    
        public virtual tabTipoArticulos tabTipoArticulos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tabCompraArticulos> tabCompraArticulos { get; set; }
    }
}
