//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TuLista.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tabCompraArticulos
    {
        public int id { get; set; }
        public Nullable<int> idAritulo { get; set; }
        public Nullable<int> idCompra { get; set; }
        public string Cantidad { get; set; }
    
        public virtual tabArticulo tabArticulo { get; set; }
        public virtual tabCompra tabCompra { get; set; }
    }
}
