//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TuLista.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tabUsuarioCompra
    {
        public int Id { get; set; }
        public Nullable<int> IdCompra { get; set; }
        public Nullable<int> IdUsuario { get; set; }
    
        public virtual tabCompra tabCompra { get; set; }
        public virtual tabUsuarios tabUsuarios { get; set; }
    }
}
